spring:
  application:
    name: langchain4j-demo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/langchain4j?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath:/mapper/**/*Mapper.xml


langchain4j:
  community:
    dashscope:
      chat-model:
       api-key: ${TONGYI_AI_KEY}
       model-name: qwen-max

      wax-image-model:
          api-key: ${TONGYI_AI_KEY}
          model-name: wanx2.1-t2i-plus
       # 流式处理引擎
      streaming-chat-model:
        api-key: ${TONGYI_AI_KEY}
        model-name: qwen-max

openweather:
    api-key: ${OPENWEATHER_KEY}
    base-url: https://api.openweathermap.org/data/2.5/weather